// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface LocationInterface {
  title:         string;
  location_type: string;
  woeid:         number;
  latt_long:     string;
}


// Generated by https://quicktype.io

export interface WeatherInterface {
  id:                     number;
  weather_state_name:     WeatherStateName;
  weather_state_abbr:     WeatherStateAbbr;
  wind_direction_compass: WindDirectionCompass;
  created:                string;
  applicable_date:        string;
  min_temp:               number;
  max_temp:               number;
  the_temp:               number;
  wind_speed:             number;
  wind_direction:         number;
  air_pressure:           number;
  humidity:               number;
  visibility:             number | null;
  predictability:         number;
}

export enum WeatherStateAbbr {
  C = "c",
  Hc = "hc",
  Lc = "lc",
}

export enum WeatherStateName {
  Clear = "Clear",
  HeavyCloud = "Heavy Cloud",
  LightCloud = "Light Cloud",
}

export enum WindDirectionCompass {
  Ssw = "SSW",
  Sw = "SW",
  Wsw = "WSW",
}
